apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  imagePullPolicy: IfNotPresent
  certificateRotateStrategy: {}
  configuration:
    permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: "1eed:1330"
        resourceName: "xdxct.com/Pangu_A0"
        externalResourceProvider: true
      mediatedDevices:
      - mdevNameSelector: xgv-XGV_V0_1G_1_CORE 
        resourceName: xdxct.com/XGV_V0_1G_1_CORE
        externalResourceProvider: true
      - mdevNameSelector: xgv-XGV_V0_128M_1_CORE 
        resourceName: xdxct.com/XGV_V0_128M_1_CORE
        externalResourceProvider: true
    imagePullPolicy: IfNotPresent
    developerConfiguration:
      featureGates:
        - GPU
        - HardDisk
        - DataVolumes
        - DisableMDEVConfiguration