---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-gpu
  name: vmi-gpu
spec:
  domain:
    cpu:
      cores: 4
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      - disk:
          bus: virtio
        name: emptydisk
      gpus:
      - deviceName: xdxct.com/Pangu_A0
        name: gpu1
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 8192M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: ucloud-kvm:20.04
    name: containerdisk
  - emptyDisk:
      capacity: 10G
    name: emptydisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        user: ubuntu
        password: 123
        chpasswd: { expire: False }
        ssh_pwauth: True
    name: cloudinitdisk
