---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-vgpu-128
  name: vmi-vgpu-128
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      gpus:
      - deviceName: xdxct.com/XGV_V0_128M_1_CORE
        name: vgpu2
        virtualGPUOptions:
          display: 
            enabled: false
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: ucloud-kvm:20.04
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        user: ubuntu
        password: 123
        chpasswd: { expire: False }
        ssh_pwauth: True
    name: cloudinitdisk
